### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not LocalFileOpener when using fsspec with `isal` installed

### ISSUE THREAD

**Issue by ifiddes** [fsspec/filesystem_spec#1007]
steps to reproduce:

1. Create a clean python environment with `fsspec` and `isal` installed.
2. Generate a gzipped file.
3. Try to open the gzipped file:

```
import fsspec
f = fsspec.open("myfile.gz", mode="rb", compression="gzip").open()
```

Leads to:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ian.fiddes/miniconda3/envs/isal_test/lib/python3.8/site-packages/fsspec/core.py", line 141, in open
    out = self.__enter__()
  File "/Users/ian.fiddes/miniconda3/envs/isal_test/lib/python3.8/site-packages/fsspec/core.py", line 110, in __enter__
    f = compress(f, mode=mode[0])
  File "/Users/ian.fiddes/miniconda3/envs/isal_test/lib/python3.8/site-packages/isal/igzip.py", line 151, in __init__
    super().__init__(filename, mode, compresslevel, fileobj, mtime)
  File "/Users/ian.fiddes/miniconda3/envs/isal_test/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
TypeError: expected str, bytes or os.PathLike object, not LocalFileOpener
```

**Comment by martindurant** [comment]
I was about to say how this is working fine for me, but now I see it's isal specific.
cc @milesgranger

**Comment by milesgranger** [comment]
I don't think I'm the right person to ping here, I don't maintain `python-isal`. 

Although side note: I'm working on Rust bindings to [ISA-L](https://github.com/intel/isa-l), so maybe [cramjam](https://github.com/milesgranger/pyrus-cramjam) will have an isal backend soon (for 0-3 compress levels).
