### ISSUE TITLE
ZIP: fail to read inside a ZIP file in 2022.8.1

### ISSUE THREAD

**Issue by lhoestq** [fsspec/filesystem_spec#1034]
Since the 2022.8.1 update, this code fails:
```python
import fsspec
url = 'zip://XNLI-1.0/xnli.test.tsv::https://dl.fbaipublicfiles.com/XNLI/XNLI-1.0.zip'
f = fsspec.open(url).open()
f.read(5)
```
It now raises:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/quentinlhoest/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 899, in read
    data = self._read1(n)
  File "/Users/quentinlhoest/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 967, in _read1
    data += self._read2(n - len(data))
  File "/Users/quentinlhoest/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 999, in _read2
    data = self._fileobj.read(n)
  File "/Users/quentinlhoest/.pyenv/versions/3.7.2/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 741, in read
    self._file.seek(self._pos)
AttributeError: 'NoneType' object has no attribute 'seek'
```

while we should get the beginning of the file (value is `b"langu"`)

**Comment by lhoestq** [comment]
It appears that the file is closed directly:
```python
>>> f
<zipfile.ZipExtFile [closed]>
```
which could explain the issue

**Comment by martindurant** [comment]
The docstring of OpenFile changed - to use `open()`, you must keep a reference to the OpenFile object. You need to do the following:
```
import fsspec
url = 'zip://XNLI-1.0/xnli.test.tsv::https://dl.fbaipublicfiles.com/XNLI/XNLI-1.0.zip'
of = fsspec.open(url)
f = of.open()
f.read(5)
```
or, better
```
import fsspec
url = 'zip://XNLI-1.0/xnli.test.tsv::https://dl.fbaipublicfiles.com/XNLI/XNLI-1.0.zip'
with fsspec.open(url) as f:
    f.read(5)
```

**Comment by lhoestq** [comment]
Thanks ! I will make the appropriate changes in the hugging face projects. Do you plan to keep it as is since this breaking change was done in a patch release ?

**Comment by martindurant** [comment]
> this breaking change was done in a patch release if I understand correctly ? Or the versioning scheme doesn't assume this kind of things ?

We use calendar versioning just so we don't have to make this distinction

**Comment by lhoestq** [comment]
Ok thanks !
