### ISSUE TITLE
Reccursion error when using `WholeFileCacheFileSystem` with `HTTPFileSystem` in `v2023.6.0`

### ISSUE THREAD

**Issue by joouha** [fsspec/filesystem_spec#1304]
I have encountered the following bug:

```bash
$ python -m http.server 8080
```

```python
In [1]: from fsspec.implementations.http import HTTPFileSystem
        fs = HTTPFileSystem()
        fs.open("http://127.0.0.1:8080/").read(21)

Out[1]: b'<!DOCTYPE HTML>\n<html'

In [2]: from fsspec.implementations.cached import WholeFileCacheFileSystem
        fs = WholeFileCacheFileSystem(target_protocol="http")
        fs.open("http://127.0.0.1:8080/").read(21)

Out[2]: Traceback (most recent call last):
          File "<stdin>", line 1, in <module>
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 447, in <lambda>
            return lambda *args, **kw: getattr(type(self), item).__get__(self)(
          File "venv/lib/python3.10/site-packages/fsspec/spec.py", line 1241, in open
            f = self._open(
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 447, in <lambda>
            return lambda *args, **kw: getattr(type(self), item).__get__(self)(
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 700, in _open
            return self._open(path, mode)
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 447, in <lambda>
            return lambda *args, **kw: getattr(type(self), item).__get__(self)(
    ... last two frames are repeated a lot ...
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 447, in <lambda>
            return lambda *args, **kw: getattr(type(self), item).__get__(self)(
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 699, in _open
            self.save_cache()
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 447, in <lambda>
            return lambda *args, **kw: getattr(type(self), item).__get__(self)(
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 192, in save_cache
            with atomic_write(fn) as f:
          File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
            return next(self.gen)
          File "venv/lib/python3.10/site-packages/fsspec/implementations/cached.py", line 856, in atomic_write
            fd, fn = tempfile.mkstemp(
          File "/usr/lib/python3.10/tempfile.py", line 334, in mkstemp
            prefix, suffix, dir, output_type = _sanitize_params(prefix, suffix, dir)
          File "/usr/lib/python3.10/tempfile.py", line 116, in _sanitize_params
            output_type = _infer_return_type(prefix, suffix, dir)
          File "/usr/lib/python3.10/tempfile.py", line 92, in _infer_return_type
            if isinstance(arg, _os.PathLike):
          File "/usr/lib/python3.10/abc.py", line 119, in __instancecheck__
            return _abc_instancecheck(cls, instance)
        RecursionError: maximum recursion depth exceeded in comparison
```

This did not happen in `v2023.5.0`.

**Comment by martindurant** [comment]
@ianthomas23 , it seems that `fs.get(str, str, recursive=False)` is not writing data to the specified output. This is because the origin URL ends with a slash, and so is being interpreted as a directory.

Furthermore, even when removing the trailing space, `_isdir()` still reports True if the URL includes links to nested URLs, as is common for HTTP, so we hit return without doing any work in fsspec.async._get:
```
        if source_is_str and (not recursive or maxdepth is not None):
            # Non-recursive glob does not copy directories
            rpaths = [
                p for p in rpaths if not (trailing_sep(p) or await self._isdir(p))
            ]
            if not rpaths:
                return
``` 
(path is NOT a glob in this case)

I have made a fix to caching in the linked PR. I don't know if there's anything to be done for the rest.

**Comment by martindurant** [comment]
Note that for the for this URL, both isdir() and isfile() return True. Using isfile(). instead might break those backends where you can have things other than files and directories.
