### ISSUE TITLE
DirFileSystem breaks open_async for any underling filesystem

### ISSUE THREAD

**Issue by vovochka404** [fsspec/filesystem_spec#1414]
DirFileSystem can wrap any async filesystem. But cause `open_async` method is not redirected to wrapped fs, it will always raise `NotImplementedError`.

As mentioned in #1411, cause all unimplemented  methods in base abstract classes got no `abstractmethod` decorator, it's hard to see that u've missed implementation on some method.

**Comment by martindurant** [comment]
open_async is experimental anyway, and there is no requirement that filesystems implement it. This is the problem with abstractmethod - in this case, NotImplemented is the right answer, since it's just waiting for someone to implement it.

**Comment by vovochka404** [comment]
But `DirFileSystem` is a wrapper. It should pass original call (with modified path) to wrapped file system. `NotImpementedError` must be thrown by wrapped (underling) fs, not by dirfs.

**Comment by martindurant** [comment]
I agree that it should be implemented, yes - it just hasn't happened yet

**Comment by dhirschfeld** [comment]
I've got a `DirFileSystem` wrapping a `LocalFileSystem` and am seeing a `NotImplementedError` when trying to use `write_bytes`.

Posting here in case the underlying issue is the same. If not it can be moved to a new issue...

```python-traceback
fs.write_bytes(filepath, blob)
Traceback (most recent call last):
  File "C:\python\envs\dev-py310\lib\site-packages\IPython\core\interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-cd365f2247d4>", line 1, in <module>
    fs.write_bytes(filepath, blob)
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\spec.py", line 1502, in write_bytes
    self.pipe_file(path, value, **kwargs)
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py", line 103, in sync
    raise return_result
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py", line 56, in _runner
    result[0] = await coro
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py", line 393, in _pipe_file
    raise NotImplementedError
NotImplementedError
```
