### ISSUE TITLE
`DirFileSystem.write_bytes` raises `NotImplementedError` 

### ISSUE THREAD

**Issue by dhirschfeld** [fsspec/filesystem_spec#1457]
I've got a `DirFileSystem` wrapping a `LocalFileSystem` and am seeing a `NotImplementedError` when trying to use `write_bytes`.

```python-traceback
fs.write_bytes(filepath, blob)
Traceback (most recent call last):
  File "C:\python\envs\dev-py310\lib\site-packages\IPython\core\interactiveshell.py", line 3548, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-cd365f2247d4>", line 1, in <module>
    fs.write_bytes(filepath, blob)
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\spec.py", line 1502, in write_bytes
    self.pipe_file(path, value, **kwargs)
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py", line 103, in sync
    raise return_result
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py", line 56, in _runner
    result[0] = await coro
  File "C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py", line 393, in _pipe_file
    raise NotImplementedError
NotImplementedError
```
Repro:
```python
In [3]: from fsspec.implementations.local import LocalFileSystem
   ...: from fsspec.implementations.dirfs import DirFileSystem

In [5]: fs = DirFileSystem(path='C:/temp', fs=LocalFileSystem())

In [6]: fs.write_bytes('/deleteme.bin', b"123")
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[6], line 1
----> 1 fs.write_bytes('/deleteme.bin', b"123")

File C:\python\envs\dev-py310\lib\site-packages\fsspec\spec.py:1502, in AbstractFileSystem.write_bytes(self, path, value, **kwargs)
   1500 def write_bytes(self, path, value, **kwargs):
   1501     """Alias of `AbstractFileSystem.pipe_file`."""
-> 1502     self.pipe_file(path, value, **kwargs)

File C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py:118, in sync_wrapper.<locals>.wrapper(*args, **kwargs)
    115 @functools.wraps(func)
    116 def wrapper(*args, **kwargs):
    117     self = obj or args[0]
--> 118     return sync(self.loop, func, *args, **kwargs)

File C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py:103, in sync(loop, func, timeout, *args, **kwargs)
    101     raise FSTimeoutError from return_result
    102 elif isinstance(return_result, BaseException):
--> 103     raise return_result
    104 else:
    105     return return_result

File C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py:56, in _runner(event, coro, result, timeout)
     54     coro = asyncio.wait_for(coro, timeout=timeout)
     55 try:
---> 56     result[0] = await coro
     57 except Exception as ex:
     58     result[0] = ex

File C:\python\envs\dev-py310\lib\site-packages\fsspec\asyn.py:393, in AsyncFileSystem._pipe_file(self, path, value, **kwargs)
    392 async def _pipe_file(self, path, value, **kwargs):
--> 393     raise NotImplementedError

NotImplementedError:
```

_Originally posted by @dhirschfeld in https://github.com/fsspec/filesystem_spec/issues/1414#issuecomment-1825166644_

**Comment by dhirschfeld** [comment]
How can I write data to a file using a `DirFileSystem`? It seems pretty core functionality for any filesystem to implement.

I could pull out the underlying filesystem and manually prepend the path to the `write_bytes` call but I'm hoping there's a cleaner workaround than that?

**Comment by dhirschfeld** [comment]
I've patched my local install with the below method:
```python
    def write_bytes(self, path, value, **kwargs):
        return self.fs.write_bytes(self._join(path), value, **kwargs)
```

This appears to work for me :tada:

If this fix is acceptable I can put in a PR?

**Comment by martindurant** [comment]
The canonical way to do this operation is `.pipe()`, which works for one or more files. It seems that DirFS defined `pipe()` but not `pipe_file`, the one-file specific version of this which is the thing that write_bytes calls. Implementing this in exactly the same way would be the right solution. (cp_file, rm_file and cat_file are all implemented, don't know why one got missed).

**Comment by dhirschfeld** [comment]
Thanks for the pointer @martindurant! I opened a PR over at https://github.com/fsspec/filesystem_spec/pull/1465

Testing locally and it seems to work great!

![image](https://github.com/fsspec/filesystem_spec/assets/881019/1edbbc26-fd53-4f23-94f6-1c67a4e1a359)
