### ISSUE TITLE
fsspec.open_local fails with AttributeError: 'AioClientCreator' in fsspec==2021.11.0

### ISSUE THREAD

**Issue by cdibble** [fsspec/filesystem_spec#818]
I'm using fsspec to get files from S3. I'm using Ubuntu 20.x in a docker environment.

After upgrading from `fsspec==2021.10.1` to `fsspec==2021.11.0`, I can no longer access weather forecasts on S3 in GRIB format that previously I retrieved successfully as follows (note these are public data so this should be reproducible).

```
import fsspec
import cfgrib
import os
bucket = 'noaa-gefs-pds'
path = 'gefs.20211104/12/atmos/pgrb2sp25/gec00.t12z.pgrb2s.0p25.f000'
uri = os.path.join('simplecache::s3://', bucket, path)
mem = fsspec.open_local(uri)
dataset = cfgrib.open_datasets(mem)
```

I get this stack trace at the `fsspec.open_local(uri)` call:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/core.py", line 487, in open_local
    with of as files:
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/core.py", line 184, in __enter__
    self.files = fs.open_many(self)
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 394, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 503, in open_many
    self.fs.get(downpath, downfn)
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 459, in _get
    return await _run_coros_in_chunks(
  File "/home/airflow/.local/lib/python3.8/site-packages/fsspec/asyn.py", line 213, in _run_coros_in_chunks
    results.append(await coro)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 619, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/home/airflow/.local/lib/python3.8/site-packages/s3fs/core.py", line 978, in _get_file
    resp = await self._call_s3(
  File "/home/airflow/.local/lib/python3.8/site-packages/s3fs/core.py", line 241, in _call_s3
    await self.set_session()
  File "/home/airflow/.local/lib/python3.8/site-packages/s3fs/core.py", line 409, in set_session
    self._s3 = await s3creator.__aenter__()
  File "/home/airflow/.local/lib/python3.8/site-packages/aiobotocore/session.py", line 37, in __aenter__
    self._client = await self._coro
  File "/home/airflow/.local/lib/python3.8/site-packages/aiobotocore/session.py", line 121, in _create_client
    client = await client_creator.create_client(
  File "/home/airflow/.local/lib/python3.8/site-packages/aiobotocore/client.py", line 46, in create_client
    self._register_lazy_block_unknown_fips_pseudo_regions(service_client)
AttributeError: 'AioClientCreator' object has no attribute '_register_lazy_block_unknown_fips_pseudo_regions'
```

Happy to provide additional info.

**Comment by cdibble** [comment]
Well I may have filed this here prematurely. Downgrading `fsspec` and/or `s3fs` doesn't solve the problem. But re-installing `aiobotocore` does solve the problem even with the latest version of `fsspec` and `s3fs`. This is probably something on my end, so I'll close this.
