### ISSUE TITLE
`local_file` attribute cannot be read from `CachingFileSystem`

### ISSUE THREAD

**Issue by ahirner** [fsspec/filesystem_spec#823]
To decide how to cache data files from an fsspec system, it's interesting to know their `local_file` attribute.
However, it is masked in __getattribute__ and becomes a lambda.
```
>>> from fsspec.implementations.cached import SimpleCacheFileSystem
>>> SimpleCacheFileSystem(target_protocol="s3").local_file
<function CachingFileSystem.__getattribute__.<locals>.<lambda> at 0x7fc924c8b940>
>>> SimpleCacheFileSystem(target_protocol="s3").local_file()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/dafcok/miniconda3/envs/vid-vision/lib/python3.8/site-packages/fsspec/implementations/cached.py", line 394, in <lambda>
    return lambda *args, **kw: getattr(type(self), item).__get__(self)(
AttributeError: 'bool' object has no attribute '__get__'
```

## Version
```
fsspec==2021.11.0
s3fs==2021.11.0
```

## Expected
```
>>> from fsspec.implementations.cached import SimpleCacheFileSystem; SimpleCacheFileSystem(target_protocol="s3").local_file
True
```

I guess the purpose of masking members in `def __getattribute__(self, item):` has something to do with serialization, yet `local_file` probably shouldn't become a lambda.

**Comment by martindurant** [comment]
Agreed, `local_file` can be among the exposed attributes. This should be an easy thing to implement, looking at the list of labels in `__getattribute__` (should probably be a set to be a bit faster).

**Comment by martindurant** [comment]
Catching up on old issues... would you like to provide the fix that I suggested above, @ahirner ?
