### ISSUE TITLE
lpath of filesystem.get doesn't handle pathlib.Path gracefully

### ISSUE THREAD

**Issue by FirefoxMetzger** [fsspec/filesystem_spec#896]
I didn't find an existing issue, so I am opening a new one. 

It looks like we can't pass pathlib Path's as local paths for get. I've only tried it against the GitHub implementation so far but considering that it fails in what appears to be a general utility function it might affect other implementations, too. Here is a reproducing example of the problem:

```python
>>> import fsspec
>>> from pathlib import Path
>>> foo = Path("test_file.md") 
>>> fs = fsspec.filesystem("github", org="fsspec", repo="filesystem_spec")
>>> fs.get("README.md", foo)      
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python38\lib\site-packages\fsspec\spec.py", line 771, in get
    lpaths = other_paths(rpaths, lpath)
  File "C:\Users\Sebastian\AppData\Local\Programs\Python\Python38\lib\site-packages\fsspec\utils.py", line 380, in other_paths
    assert len(paths) == len(path2)
TypeError: object of type 'WindowsPath' has no len()
>>> fs.get("README.md", str(foo))  # this works fine
>>>
```

 

Would it be possible to allow inputs of type pathlib.path for `lpath`? (e.g., by simply converting them to posix path strings: `lpath.as_posix()`)

**Comment by martindurant** [comment]
It would be possible, but annoying, as this would have to be done in several place. Plus, `Path` objects only refer to *local* paths, whereas other libraries (like `universal_pathlib`) work with full fsspec paths - complicating the picture. I think it would be very reasonable to apply this in #828 , where a few specific functions dispatch to the various implementations.

**Comment by FirefoxMetzger** [comment]
Yes, certainly `pathlib` has its limitations especially in this context where the scope is explicitly beyond that of a local filesystem. Nevertheless, it is part of the standard library, so I think it will keep popping up until it is addressed.

It's also reasonable that you only want to deal with one type of object inside the library because everything else makes life complicated. Perhaps there could be something like a `normalize_path` utility that does the work in one central place and is called by/decorates relevant functions?

**Comment by martindurant** [comment]
There is such a function, `fsspec.implementations.local.stringify_path`, but the point is it might need to be called from a lot of places. See also `fsspec.implementations.local.make_path_posix`, both of which are called by `LocalFileSystem._strip_protocol`.
