### ISSUE TITLE
S3FileSystem or AioSession is not expecting to get a `storage_options` keyword argument

### ISSUE THREAD

**Issue by jpivarski** [fsspec/filesystem_spec#920]
In version 2022.02.0 and the HEAD of `fsspec` and `s3fs`, calling

```python
import fsspec.parquet
fsspec.parquet.open_parquet_file(
    "s3://pivarski-princeton/millionsongs/millionsongs-A-zstd.parquet",
    columns=["hdf5_filename", "analysis.bars.list.item.confidence"],
)
```

raises

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/irishep/filesystem_spec/fsspec/parquet.py", line 111, in open_parquet_file
    data = _get_parquet_byte_ranges(
  File "/home/jpivarski/irishep/filesystem_spec/fsspec/parquet.py", line 181, in _get_parquet_byte_ranges
    file_sizes = fs.sizes(paths)
  File "/home/jpivarski/irishep/filesystem_spec/fsspec/asyn.py", line 85, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/home/jpivarski/irishep/filesystem_spec/fsspec/asyn.py", line 65, in sync
    raise return_result
  File "/home/jpivarski/irishep/filesystem_spec/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/home/jpivarski/irishep/filesystem_spec/fsspec/asyn.py", line 541, in _sizes
    return await _run_coros_in_chunks(
  File "/home/jpivarski/irishep/filesystem_spec/fsspec/asyn.py", line 241, in _run_coros_in_chunks
    await asyncio.gather(*chunk, return_exceptions=return_exceptions),
  File "/home/jpivarski/mambaforge/lib/python3.9/asyncio/tasks.py", line 442, in wait_for
    return await fut
  File "/home/jpivarski/irishep/filesystem_spec/fsspec/asyn.py", line 537, in _size
    return (await self._info(path)).get("size", None)
  File "/home/jpivarski/irishep/s3fs/s3fs/core.py", line 1065, in _info
    out = await self._call_s3(
  File "/home/jpivarski/irishep/s3fs/s3fs/core.py", line 273, in _call_s3
    await self.set_session()
  File "/home/jpivarski/irishep/s3fs/s3fs/core.py", line 416, in set_session
    self.session = aiobotocore.session.AioSession(**self.kwargs)
TypeError: __init__() got an unexpected keyword argument 'storage_options'
```

because AioSession only takes these arguments:

https://github.com/aio-libs/aiobotocore/blob/4c150b26ad337ee5561c2d2b10e3c6c9cb7a1e2f/aiobotocore/session.py#L47-L48

The `self.kwargs` passed to AioSession is set in the constructor of S3FileSystem:

https://github.com/fsspec/s3fs/blob/4f289eaa34dfe8337a72f5a0148c41a44793fde0/s3fs/core.py#L234

and this contains `storage_options` because fsspec put it there in `url_to_fs`:

https://github.com/fsspec/filesystem_spec/blob/fe09da6942ad043622212927df7442c104fe7932/fsspec/core.py#L405-L407

Removing just that `update_storage_options` call makes `open_parquet_file` work:

```python
>>> fsspec.parquet.open_parquet_file(
...     "s3://pivarski-princeton/millionsongs/millionsongs-A-zstd.parquet",
...     columns=["hdf5_filename", "analysis.bars.list.item.confidence"],
... )
<File-like object S3FileSystem, pivarski-princeton/millionsongs/millionsongs-A-zstd.parquet>
```

though I don't know if this is the right place to remove it. (Perhaps it should pass through to S3FileSystem but not get propagated to AioSession?)

**Comment by martindurant** [comment]
@rjzamora , can you advise on how to call fsspec.parquet correctly *without* dask?

**Comment by jpivarski** [comment]
I see what happened: I didn't pass an `fs` argument. The bug-report probably stands, because the function doesn't work with its default arguments, though I can see how it might have only ever been tested with an explicit `fs` argument.

This works:

```python
>>> import fsspec
>>> import fsspec.parquet
>>> fs, _, _ = fsspec.get_fs_token_paths(
...     "s3://pivarski-princeton/millionsongs/millionsongs-A-zstd.parquet",
...     mode="rb",
... )
>>> fsspec.parquet.open_parquet_file(
...     "s3://pivarski-princeton/millionsongs/millionsongs-A-zstd.parquet",
...     columns=["hdf5_filename", "analysis.bars.list.item.confidence"],
...     fs=fs,    #  <-------
... )
<File-like object S3FileSystem, pivarski-princeton/millionsongs/millionsongs-A-zstd.parquet>
```

**Comment by martindurant** [comment]
OK, let's close this as an issue, with a reminder to self for better docs and/or input validation for open_parquet_file.

**Comment by rjzamora** [comment]
Ah - Sorry for arriving here late. I think @jpivarski is correct that this has never been tested on s3 without the explicit `fs=` argument. I would have expected the `fs` inference to work, so I'd still like to figure out what is going wrong here.

**Comment by martindurant** [comment]
Ah, I see:
```
    if fs is None:
        fs = url_to_fs(path, storage_options=(storage_options or {}))[0]
```
should be
```
    if fs is None:
        fs = url_to_fs(path, **(storage_options or {}))[0]
```
